### ISSUE TITLE
gen-arch_n1.sh这个脚本只能在arm架构主机上运行吧？打包或者安装软件的效率会不会比较低？

### ISSUE THREAD

**Issue by yjxch** [yangxuan8282/gen-rpi_os#1]

**Comment by yangxuan8282** [comment]
arm 上速度还可以，alpine 不带桌面的版本不到5分钟可以生成完，当然 debian 和 arch 这些就慢很多，更多的其实是看网速，qemu 模拟 arm 的效率其实是比较低的，比原生应该会更慢，之前编译 docker 镜像时候就是用的 qemu ，只要是稍微新的板子应该都是直接原生运行更好

**Comment by yjxch** [comment]
谢谢
