### ISSUE TITLE
apk.static: not found

### ISSUE THREAD

**Issue by jposemescouilles** [yangxuan8282/gen-rpi_os#5]
I am trying to build alpine image for my odroid xu4.

I am building on Ubuntu 18.10 minimal on a google compute instance (maybe should I build natively on my xu4 ?)

I get this error : 

+ apk.static -X https://mirrors.tuna.tsinghua.edu.cn/alpine/edge/main -U --allow-untrusted --root mnt --initdb add alpine-base
./gen-alpine_xu4.sh: 87: ./gen-alpine_xu4.sh: apk.static: not found

I have no idea how to solve it

**Comment by yangxuan8282** [comment]
the `gen-alpine_xu4.sh` assume you run it on alpine, and have installed `apk-tools-static`
for other distros like ubuntu should run `sudo ./gen-chroot.sh xu4-alpine`, that will generate alpine rootfs and build img inside it

besides those scripts didn't add qemu support, you should run them on arm or add qemu binary manually

**Comment by jposemescouilles** [comment]
will do

thank you
